/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { FoodItem, FoodItem$ } from "./fooditem";
import { z } from "zod";

export type Meal = {
    name?: string | undefined;
    items?: Array<FoodItem> | undefined;
};

/** @internal */
export namespace Meal$ {
    export type Inbound = {
        name?: string | undefined;
        items?: Array<FoodItem$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<Meal, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string().optional(),
            items: z.array(FoodItem$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });

    export type Outbound = {
        name?: string | undefined;
        items?: Array<FoodItem$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Meal> = z
        .object({
            name: z.string().optional(),
            items: z.array(FoodItem$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });
}
