/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type NutritionInformation = {
    calories?: number | undefined;
    protein?: number | undefined;
    carbohydrates?: number | undefined;
    fat?: number | undefined;
};

/** @internal */
export namespace NutritionInformation$ {
    export type Inbound = {
        calories?: number | undefined;
        protein?: number | undefined;
        carbohydrates?: number | undefined;
        fat?: number | undefined;
    };

    export const inboundSchema: z.ZodType<NutritionInformation, z.ZodTypeDef, Inbound> = z
        .object({
            calories: z.number().optional(),
            protein: z.number().optional(),
            carbohydrates: z.number().optional(),
            fat: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.calories === undefined ? null : { calories: v.calories }),
                ...(v.protein === undefined ? null : { protein: v.protein }),
                ...(v.carbohydrates === undefined ? null : { carbohydrates: v.carbohydrates }),
                ...(v.fat === undefined ? null : { fat: v.fat }),
            };
        });

    export type Outbound = {
        calories?: number | undefined;
        protein?: number | undefined;
        carbohydrates?: number | undefined;
        fat?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NutritionInformation> = z
        .object({
            calories: z.number().optional(),
            protein: z.number().optional(),
            carbohydrates: z.number().optional(),
            fat: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.calories === undefined ? null : { calories: v.calories }),
                ...(v.protein === undefined ? null : { protein: v.protein }),
                ...(v.carbohydrates === undefined ? null : { carbohydrates: v.carbohydrates }),
                ...(v.fat === undefined ? null : { fat: v.fat }),
            };
        });
}
