/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type NutritionAnalysis = {
    /**
     * Total calories for the week
     */
    totalCalories?: number | undefined;
    /**
     * Total protein for the week
     */
    totalProtein?: number | undefined;
    /**
     * Total carbohydrates for the week
     */
    totalCarbohydrates?: number | undefined;
    /**
     * Total fat for the week
     */
    totalFat?: number | undefined;
};

/** @internal */
export namespace NutritionAnalysis$ {
    export type Inbound = {
        totalCalories?: number | undefined;
        totalProtein?: number | undefined;
        totalCarbohydrates?: number | undefined;
        totalFat?: number | undefined;
    };

    export const inboundSchema: z.ZodType<NutritionAnalysis, z.ZodTypeDef, Inbound> = z
        .object({
            totalCalories: z.number().optional(),
            totalProtein: z.number().optional(),
            totalCarbohydrates: z.number().optional(),
            totalFat: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.totalCalories === undefined ? null : { totalCalories: v.totalCalories }),
                ...(v.totalProtein === undefined ? null : { totalProtein: v.totalProtein }),
                ...(v.totalCarbohydrates === undefined
                    ? null
                    : { totalCarbohydrates: v.totalCarbohydrates }),
                ...(v.totalFat === undefined ? null : { totalFat: v.totalFat }),
            };
        });

    export type Outbound = {
        totalCalories?: number | undefined;
        totalProtein?: number | undefined;
        totalCarbohydrates?: number | undefined;
        totalFat?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NutritionAnalysis> = z
        .object({
            totalCalories: z.number().optional(),
            totalProtein: z.number().optional(),
            totalCarbohydrates: z.number().optional(),
            totalFat: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.totalCalories === undefined ? null : { totalCalories: v.totalCalories }),
                ...(v.totalProtein === undefined ? null : { totalProtein: v.totalProtein }),
                ...(v.totalCarbohydrates === undefined
                    ? null
                    : { totalCarbohydrates: v.totalCarbohydrates }),
                ...(v.totalFat === undefined ? null : { totalFat: v.totalFat }),
            };
        });
}
